import React from "react";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";
import { Cpu, CheckCircle2, Wrench, ChevronRight, Sparkles, TimerReset, GitBranch, Info, ArrowUpRight } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { RiskPill } from "@/components/RiskPill";

export default function PredictiveInsights() {
  const fleetQuery = trpc.fleet.list.useQuery();
  const fleet = fleetQuery.data || [];
  const flaggedMachines = fleet.filter((machine) => machine.riskAssessment.riskCategory !== "LOW").sort((a, b) => b.riskAssessment.estimatedRiskPct - a.riskAssessment.estimatedRiskPct);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white flex items-center space-x-2.5"><Cpu className="w-6 h-6 text-amber-400" /><span>Predictive Intelligence</span></h1><p className="text-sm text-slate-400 mt-1">Health score, anomaly evidence, probable issue, degradation estimate, and recommended action.</p></div><Link href="/simulation"><Button size="sm" className="bg-amber-500 hover:bg-amber-400 text-slate-950 font-semibold text-xs"><Sparkles className="w-3.5 h-3.5 mr-1.5" />Run Risk Scenario</Button></Link></div>

      <Card className="bg-gradient-to-r from-slate-900 via-slate-900 to-slate-950 border-amber-500/20"><CardContent className="p-4 sm:p-5"><div className="flex items-start gap-2"><Info className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" /><div><div className="text-xs font-mono font-bold text-amber-400 uppercase tracking-wider">Hybrid intelligence pipeline</div><p className="text-xs text-slate-300 leading-relaxed mt-1">Rules and engineering-inspired thresholds identify obvious abnormal states. Trend and multi-sensor evidence add anomaly context. Probable faults are hypotheses, not diagnoses. RUL is a clearly labelled demo estimate until run-to-failure data is connected.</p></div></div></CardContent></Card>

      <div className="space-y-4">{flaggedMachines.length === 0 ? <Card className="bg-slate-900/90 border-slate-800 p-12 text-center space-y-3"><CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto" /><h2 className="text-base font-bold text-white">All Monitored Assets in Nominal Condition</h2><p className="text-xs text-slate-400">Launch the interactive demo to replay a coherent degradation sequence.</p><Link href="/simulation"><Button className="bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-semibold">Launch Demo</Button></Link></Card> : flaggedMachines.map((machine, index) => { const risk = machine.riskAssessment; const primaryFault = risk.probableFaults[0]; return <Card key={machine.id} className={`border-slate-800 overflow-hidden ${risk.riskCategory === "CRITICAL" ? "border-red-500/40" : ""}`}><div className="p-4 sm:p-5 border-b border-slate-800 bg-slate-950/40 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="w-7 h-7 rounded flex items-center justify-center font-mono font-bold text-xs bg-amber-500/15 text-amber-400 border border-amber-500/30">#{index + 1}</span><div><div className="flex flex-wrap items-center gap-2"><Link href={`/machine/${machine.id}`} className="text-base font-bold text-white hover:text-amber-400">{machine.name}</Link><span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-slate-800 text-amber-400 border border-slate-700">{machine.id}</span></div><div className="text-xs text-slate-400 font-mono mt-0.5">Health {risk.healthScorePct}/100 • Priority {risk.maintenancePriority} • {machine.dataSource}</div></div></div><div className="flex items-center gap-3"><RiskPill category={risk.riskCategory} pct={risk.estimatedRiskPct} /><Link href={`/machine/${machine.id}`}><Button size="sm" variant="outline" className="h-8 text-xs border-slate-700 hover:bg-slate-800">Deep Dive <ChevronRight className="w-3.5 h-3.5 ml-1" /></Button></Link></div></div><CardContent className="p-4 sm:p-5 space-y-4">
          <div className="p-3.5 bg-slate-950/80 rounded border border-slate-800"><div className="text-xs font-bold text-amber-400 uppercase tracking-wide font-mono flex items-center gap-1.5"><Cpu className="w-3.5 h-3.5" />Detected condition & evidence</div><p className="text-xs sm:text-sm text-slate-200 leading-relaxed mt-1">{risk.explanation}</p></div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-2"><div className="p-3 rounded bg-slate-950 border border-slate-800"><div className="text-[10px] uppercase font-mono text-slate-500">Detected anomaly</div><div className="text-sm font-semibold text-amber-300 mt-1">{risk.primaryAnomaly}</div><div className="text-[11px] text-slate-400 mt-1">Trend: {risk.degradationTrend}</div></div><div className="p-3 rounded bg-slate-950 border border-slate-800"><div className="text-[10px] uppercase font-mono text-slate-500 flex items-center gap-1"><GitBranch className="w-3 h-3" />Predicted probable issue</div><div className="text-sm font-semibold text-slate-100 mt-1">{primaryFault?.label}</div><div className="text-[11px] text-slate-400 mt-1">{primaryFault?.probabilityPct}% relative evidence</div></div><div className="p-3 rounded bg-slate-950 border border-slate-800"><div className="text-[10px] uppercase font-mono text-slate-500 flex items-center gap-1"><TimerReset className="w-3 h-3" />Projected degradation window</div><div className="text-sm font-semibold text-sky-300 mt-1">{risk.rulEstimate.label}</div><div className="text-[11px] text-slate-400 mt-1">{risk.rulEstimate.basis}</div></div></div>
          <div className="space-y-2"><span className="text-xs font-mono uppercase tracking-wider text-slate-400 font-semibold">Why? / Health factor attribution</span><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">{risk.healthFactors.filter((factor) => factor.contributionPct > 0).sort((a, b) => b.contributionPct - a.contributionPct).slice(0, 6).map((factor) => <div key={factor.key} className="p-3 rounded bg-slate-950 border border-slate-800 text-xs"><div className="flex items-center justify-between"><span className="font-semibold text-slate-100">{factor.label}</span><span className={`font-mono font-bold ${factor.contributionPct >= 20 ? "text-red-400" : "text-amber-400"}`}>+{factor.contributionPct}%</span></div><div className="text-[11px] text-slate-300 font-mono mt-1">{factor.observedValue}</div><div className="text-[10px] text-slate-500 font-mono">Nominal: {factor.nominalRange} • {factor.basis}</div></div>)}</div></div>
          <div className="p-3 bg-amber-500/10 rounded border border-amber-500/40 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="text-xs font-bold text-amber-300 uppercase tracking-wide font-mono flex items-center gap-1.5"><Wrench className="w-3.5 h-3.5" />Recommended maintenance action</div><p className="text-xs text-slate-200 font-medium mt-1">{risk.recommendedAction}</p></div><span className="shrink-0 text-xs font-mono font-bold text-red-300">{risk.urgency}</span></div>
        </CardContent></Card>; })}</div>
    </div>
  );
}
